<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7c8e77cb-5b03-4ef6-9127-deccad5112f6</elementGuidId>
    <imagePath></imagePath>
    <name>link_TryForFree</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'signup_link') and equals(@href,'https://www.salesforce.com/uk/form/trial/freetrial.jsp?d=70130000000DYtl') and equals(@text,'Try for Free')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Try for Free"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://www.salesforce.com/uk/form/trial/freetrial.jsp?d=70130000000DYtl</value>
        <webElementGuid>99d1fdf8-9b85-4197-a9e4-f1376d67d0d4</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>signup_link</value>
        <webElementGuid>99d1fdf8-9b85-4197-a9e4-f1376d67d0d4</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Try for Free</value>
        <webElementGuid>99d1fdf8-9b85-4197-a9e4-f1376d67d0d4</webElementGuid>
    </webElementProperties>
</WebElementEntity>