<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f0c44dec-6c2e-4038-b896-665ae35b90c2</elementGuidId>
    <imagePath></imagePath>
    <name>link_ForgotYourPassword</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'forgot_password_link') and equals(@href,'/secur/forgotpassword.jsp?locale=in&amp;lqs=locale%3Din') and equals(@text,'Forgot Your Password?')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Forgot Your Password?"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/secur/forgotpassword.jsp?locale=in&amp;lqs=locale%3Din</value>
        <webElementGuid>99d1fdf8-9b85-4197-a9e4-f1376d67d0d4</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>forgot_password_link</value>
        <webElementGuid>99d1fdf8-9b85-4197-a9e4-f1376d67d0d4</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Forgot Your Password?</value>
        <webElementGuid>99d1fdf8-9b85-4197-a9e4-f1376d67d0d4</webElementGuid>
    </webElementProperties>
</WebElementEntity>