<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1f3aae76-f29b-4f7a-88f9-8aa747cd0ead</elementGuidId>
    <imagePath></imagePath>
    <name>link_ResendEmail</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/p[3]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'resend-email') and equals(@href,'/secur/forgotpassword.jsp') and equals(@text,'resend the email')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="resend the email"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/secur/forgotpassword.jsp</value>
        <webElementGuid>99d1fdf8-9b85-4197-a9e4-f1376d67d0d4</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>resend-email</value>
        <webElementGuid>99d1fdf8-9b85-4197-a9e4-f1376d67d0d4</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>resend the email</value>
        <webElementGuid>99d1fdf8-9b85-4197-a9e4-f1376d67d0d4</webElementGuid>
    </webElementProperties>
</WebElementEntity>